# LN vs BN:

In [1]:
import numpy as np

# Toy input: batch of 2 samples, each with 4 features
x = np.array([[1.0, 2.0, 3.0, 4.0],
              [2.0, 3.0, 4.0, 5.0]])

# -- Batch Normalization (per-feature across batch) --
mean_batch = np.mean(x, axis=0)             # Compute mean for each feature across samples
var_batch  = np.var(x, axis=0)              # Compute variance for each feature
x_norm_bn  = (x - mean_batch) / np.sqrt(var_batch + 1e-5)

# -- Layer Normalization (per-sample across features) --
mean_layer = np.mean(x, axis=1, keepdims=True)  # Mean of each sample
var_layer  = np.var(x, axis=1, keepdims=True)   # Variance of each sample
x_norm_ln  = (x - mean_layer) / np.sqrt(var_layer + 1e-5)

print("BatchNorm output:\n", x_norm_bn)
print("LayerNorm output:\n", x_norm_ln)

BatchNorm output:
 [[-0.99998 -0.99998 -0.99998 -0.99998]
 [ 0.99998  0.99998  0.99998  0.99998]]
LayerNorm output:
 [[-1.34163542 -0.44721181  0.44721181  1.34163542]
 [-1.34163542 -0.44721181  0.44721181  1.34163542]]
